version: '3'

services:
  apache:
    image: 'httpd:latest'
    volumes:
      - ./html/:/usr/local/apache2/htdocs/
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:demo.netwerkdigitaalerfgoed.nl;PathPrefix:/stories;PathPrefixStrip:/stories"
      - "traefik.port=80"
    networks:
      - traefik
networks:
  traefik:
    external: true

