apiVersion: apps/v1
kind: Deployment
metadata:
  name: nde-stories-deployment
  labels:
    app: nde-stories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nde-stories
  template:
    metadata:
      labels:
        app: nde-stories
    spec:
      containers:
        - name: nde-stories
          image: clariahacr.azurecr.io/nde-stories:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockercreds

---
apiVersion: v1
kind: Service
metadata:
  name: nde-stories-service
spec:
  selector:
    app: nde-stories
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
